steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app:$COMMIT_SHA', '.'
    ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app:$COMMIT_SHA']

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 'image', 'deployment/my-app',
      'my-app=asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app:$COMMIT_SHA'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-k8-cluster'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app:$COMMIT_SHA'
