substitutions:
  _CLUSTER: "my-k8-cluster"
  _REGION: "asia-south1"
  _REPO: "my-docker-repo"
  _APP: "my-app"

steps:
  # Step 1: Build image tagged with COMMIT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP}:${COMMIT_SHA}',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP}:${COMMIT_SHA}'
      ]

  # Step 3: Deploy new image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set', 'image', 'deployment/${_APP}',
        '${_APP}=asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP}:${COMMIT_SHA}'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

  # Step 4: Verify rollout (optional)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'status', 'deployment/${_APP}']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP}:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
