name: Deploy React App to EC2 with Nginx

on:
  push:
    branches:
      - main   # deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Copy build folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/*"
          target: "~/react-build-temp/"

      - name: Deploy build to Nginx
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/react-app/*
            sudo cp -r ~/react-build-temp/* /var/www/react-app/
            sudo systemctl restart nginx
            echo "✅ Deployment completed. App running at http://13.233.112.253"
